apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- apps_v1_daemonset_node-exporter.yaml
- networking.k8s.io_v1_networkpolicy_node-exporter.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_node-exporter.yaml
- rbac.authorization.k8s.io_v1_clusterrole_node-exporter.yaml
- v1_serviceaccount_node-exporter.yaml
- v1_service_node-exporter.yaml
