apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- apiextensions.k8s.io_v1_customresourcedefinition_dnsendpoints.externaldns.nginx.org.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_globalconfigurations.k8s.nginx.org.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_policies.k8s.nginx.org.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_transportservers.k8s.nginx.org.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_virtualserverroutes.k8s.nginx.org.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_virtualservers.k8s.nginx.org.yaml
- apps_v1_daemonset_nginx-ingress.yaml
- networking.k8s.io_v1_ingressclass_nginx.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_nginx-ingress.yaml
- rbac.authorization.k8s.io_v1_clusterrole_nginx-ingress.yaml
- v1_configmap_nginx-config.yaml
- v1_namespace_nginx-ingress.yaml
- v1_serviceaccount_nginx-ingress.yaml
- v1_service_nginx-ingress.yaml
